### ISSUE TITLE
Pupa

### ISSUE THREAD

**Issue by laurenfidler** [nvs-vocabs/S11#10]
Term name (PrefLabel)
Pupa

Definition
The life stage of some insects undergoing transformation between immature and mature stages. The pupal stage is found only in holometabolous insects, those that undergo a complete metamorphosis. The processes of entering and completing the pupal stage are controlled by the insect's hormones, especially juvenile hormone, prothoracicotropic hormone, and ecdysone.

Sources/references
Borror, D. J.; DeLong, Dwight M.; Triplehorn, Charles A. (2004). Introduction to the Study of Insects (Sixth ed.).

**Comment by gwemon** [comment]
@laurenfidler The following term has been added to S11 and will be published on 16/11/2019 as http://vocab.nerc.ac.uk/collection/S11/current/S1180
