### ISSUE TITLE
NTR: Request for S11 Chalimus

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S11#11]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Chalimus <p><b>Definition</b><p> The life stages of parasitic copepod species marked by their secure attachment to a host by a frontal filament. The chalimus stages follow the free-swimming copepodid stage and precede the sub-adult stages where the organism is capable of detaching from its filament to move across the surface of its host. <p><H2> Optional </H2><p><b>Sources/references</b><p> https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0073539https://www.sciencedirect.com/science/article/pii/S0165783605001785<p> <b>Mapping to other terminologies </b><p> Follows S115 (copepodites) http://vocab.nerc.ac.uk/collection/S11/current/S115/ <p>

**Comment by gwemon** [comment]
The term has been added to the NVS as http://vocab.nerc.ac.uk/collection/S11/current/S1182
It will be published overnight shortly after 0200AM UT

**Comment by nbekolay** [comment]
Thank you, Gwen!
