### ISSUE TITLE
NTR: Request for S11 praniza (BODCNVS-925)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S11#15]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>praniza <p><b>Definition</b><p> The juvenile form of a family of marine isopod crustaceans known as Gnathiidae. The adults are associated with sponges and occur in a wide of depths. The praniza 'larva' is a temporary parasite of marine fishes.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://en.wikipedia.org/wiki/Gnathiidae and requesters<p> <b>ORCID</b><p> gwemon<p>

**Comment by gwemon** [comment]
New term added to the NVS and queued for publication at around 0730 BST tomorrow.

**Comment by gwemon** [comment]
This term is now published: http://vocab.nerc.ac.uk/collection/S11/current/S1191/
