### ISSUE TITLE
NTR: Request for S11 Middle stage of egg

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S11#17]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Middle stage of egg <p><b>Definition</b><p> From the beginning to the end of epiboly<p><H2> Optional </H2><p><b>Sources/references</b><p> Moser, H. G. (Ed.). (1996). The early stages of fishes in the California Current region. US Department of the Interior, Minerals Management Service, Pacific OCS Region. || Ahlstrom, E.H. and O.P. Ball. (1954). Description of eggs and larvae of jack mackerel (Trachurus symmetricus) and distribution and abundance of larvae in 1950 and 1951. Fish. Bull. 56:209-245. || Kendall, Jr. A.W, Ahlstrom, E.H. and Moser, H.G. (1984). Early life history stages of fishes and their characters, American Society of Ichthyologists and Herpetologists, Special publication 1: 11–22.<p>

**Comment by roswri** [comment]
Suggested term: 

Term name (PrefLabel): Middle stage of egg
Definition: An embryonic development stage from the beginning to the end of gastrulation.

**Comment by gwemon** [comment]
see comment in https://github.com/nvs-vocabs/S11/issues/18

**Comment by danibodc** [comment]
We have now created the following term:

S1185 - middle stage eggs
An embryonic development stage from the beginning to the end of gastrulation.

Note that this will not become live on the NVS until ~0730UT tomorrow.

**Comment by danibodc** [comment]
This term is now live on the NVS:
http://vocab.nerc.ac.uk/collection/S11/current/S1185/
