### ISSUE TITLE
NTR: Request for S11 Yolk-Sac Larval Stage (BODCNVS-933)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S11#19]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Yolk-Sac Larval Stage <p><b>Definition</b><p> Developmental stage between hatching and yolk-sac absorption.<p><H2> Optional </H2><p><b>Sources/references</b><p> Ahlstrom, E.H. and O.P. Ball. (1954). Description of eggs and larvae of jack mackerel (Trachurus symmetricus) and distribution and abundance of larvae in 1950 and 1951. Fish. Bull. 56:209-245. || Kendall, Jr. A.W, Ahlstrom, E.H. and Moser, H.G. (1984). Early life history stages of fishes and their characters. American Society of Ichthyologists and Herpetologists, Special publication 1: 11–22.<p>

**Comment by gwemon** [comment]
See also NOAA's ichtyoplankton LIFE HISTORY STAGE DEFINITIONS: https://access.afsc.noaa.gov/ichthyo/StageDefPage.php

**Comment by gwemon** [comment]
Recommending lower case for the preferred label and continue using the plural form  to be consistent with existing S11 content.

**Term name (PrefLabel)**: yolk-sac larvae
**Definition**: An ichthyoplankton life stage between hatching and until complete absorption of yolk sac.

**Comment by danibodc** [comment]
We have now created the following term:

S1187 yolk-sac larvae
A fish life stage between hatching and until complete absorption of yolk-sac.

We chose 'fish' as opposed to 'icythoplankton' in the definition to match FishBase: https://www.fishbase.se/glossary/Glossary.php?q=flexion+larva&sc=is

This term is now live on the NVS:
http://vocab.nerc.ac.uk/collection/S11/current/S1187/
