### ISSUE TITLE
NTR: Request for S11 Juvenile stage (BODCNVS-933)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S11#23]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Juvenile stage <p><b>Definition</b><p> Completion of fin ray counts and beginning of squamation until fish enters adult population or attains sexual maturity.<p><H2> Optional </H2><p><b>Sources/references</b><p> Ahlstrom, E.H. and O.P. Ball. (1954). Description of eggs and larvae of jack mackerel (Trachurus symmetricus) and distribution and abundance of larvae in 1950 and 1951. Fish. Bull. 56:209-245. || Kendall, Jr. A.W, Ahlstrom, E.H. and Moser, H.G.(1984). Early life history stages of fishes and their characters, American Society of Ichthyologists and Herpetologists, Special publication 1: 11–22.<p>

**Comment by gwemon** [comment]
The life stage "juvenile" has already been defined in S11: http://vocab.nerc.ac.uk/collection/S11/current/S1127/
