### ISSUE TITLE
NTR: First-juvenile instar [BODCNVS-1917]

### ISSUE THREAD

**Issue by timvdstap** [nvs-vocabs/S11#26]
### Term name (PrefLabel)

First juvenile instar

### Definition

Larval development typically consists of series of stages in which each stage is separated from the next by a molt. An instar is usually defined as the period between molts (ecdyses), and synonymous to the first developmental phase in the juvenile lifestage. The first-juvenile instar is the first developmental phase for certain juvenile arthropods and crustaceans. 

@heather-earle - please advise if this definition needs tweaking. 

### Sources/references
Atlas of Crustacean Larvae: https://www.researchgate.net/publication/263235775_Atlas_of_Crustacean_Larvae
Larval Development and Molting: https://www.intechopen.com/chapters/69159
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3777888/

### Synonym or acronym (AltLabel)

first-instar juvenile
first larval instar stage

### Mapping to external terminologies
Not really an external terminology - but a Dungeness Crab Research Group in Puget Sound that uses first-juvenile instar as a lifestage as well: https://www.pnwcrab.com/about-dungeness-crab

### ORCID

0000-0002-0053-0795

**Comment by timvdstap** [comment]
Hi @gwemon I was wondering whether you and your team perhaps have had the chance to view this issue? :)

**Comment by gwemon** [comment]
Hi @timvdstap really sorry it looks like this was missed out. It's now on our list. We'll have it done asap.

**Comment by timvdstap** [comment]
Awesome, thank you!

**Comment by roswri** [comment]
Term queued for publication: S1105 - first juvenile instar

**Comment by roswri** [comment]
https://vocab.nerc.ac.uk/collection/S11/current/S1105/
