### ISSUE TITLE
NTR: Request for S11 doliolaria

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S11#27]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>doliolaria <p><b>Definition</b><p> the second stage of larval development of holothurians (sea cucumbers)<p><H2> Optional </H2><p>

**Comment by jakjonbodc** [comment]
linked to https://github.com/nvs-vocabs/P01/issues/209

**Comment by jakjonbodc** [comment]
S11 term created for doliolaria - S1199

**Comment by jakjonbodc** [comment]
http://vocab.nerc.ac.uk/collection/S11/current/S1199/
