### ISSUE TITLE
NTR: Request for S11 actinotroch

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S11#28]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>actinotroch <p><b>Definition</b><p> Free-swimming larvae of Phoronida<p><H2> Optional </H2><p>

**Comment by jakjonbodc** [comment]
https://github.com/nvs-vocabs/P01/issues/209

**Comment by jakjonbodc** [comment]
S11 term created for actinotroch - S1113

**Comment by jakjonbodc** [comment]
http://vocab.nerc.ac.uk/collection/S11/current/S1113/
