### ISSUE TITLE
NTR: Request for S11 pilidium larvae

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S11#30]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>pilidium larvae <p><b>Definition</b><p> Larval stage of both Nemertea and Spiralia in which the developing juvenile has a gut which lies across the larva's body, and usually eats the remains of the larva when it emerges.<p><H2> Optional </H2><p>

**Comment by jakjonbodc** [comment]
https://github.com/nvs-vocabs/P01/issues/209

**Comment by jakjonbodc** [comment]
S11 term created for pilidium larvae - S1102

**Comment by jakjonbodc** [comment]
http://vocab.nerc.ac.uk/collection/S11/current/S1102/
