### ISSUE TITLE
NTR: Request for S11 actinula

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S11#31]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>actinula <p><b>Definition</b><p> Larval stage of a hydrozoan cnidarian which develops into another medusa or polyp.<p><H2> Optional </H2><p>

**Comment by jakjonbodc** [comment]
https://github.com/nvs-vocabs/P01/issues/209

**Comment by jakjonbodc** [comment]
S11 term created for actinula - S1103

**Comment by jakjonbodc** [comment]
http://vocab.nerc.ac.uk/collection/S11/current/S1103/
